apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - leaderboard-svc.yml
  - leaderboardstreams.yml

images:
  - name: dedovicnermin/leaderboardstreams
    newTag: 0.0.6

configMapGenerator:
  - name: leaderboard-streams-cfg
    behavior: create
    files:
      - application.properties

