apiVersion: v1
kind: Service
metadata:
  name: leaderboards-streams-svc
  labels:
    app: leaderboard-streams
spec:
  selector:
    app: leaderboard-streams
  ports:
    - port: 7000
      name: rest
      protocol: TCP
    - port: 7778
      name: exporter
      protocol: TCP
    - port: 7203
      name: jmx
      protocol: TCP
