/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.nermdev.schemas.avro.leaderboards;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** P(player)P(roduct)ID - schema meant to represent the key of a KafkaRecord */
@org.apache.avro.specific.AvroGenerated
public class PPID extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7103384495643270209L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PPID\",\"namespace\":\"io.nermdev.schemas.avro.leaderboards\",\"doc\":\"P(player)P(roduct)ID - schema meant to represent the key of a KafkaRecord\",\"fields\":[{\"name\":\"playerId\",\"type\":\"long\"},{\"name\":\"productId\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PPID> ENCODER =
      new BinaryMessageEncoder<PPID>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PPID> DECODER =
      new BinaryMessageDecoder<PPID>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PPID> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PPID> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PPID> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PPID>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PPID to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PPID from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PPID instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PPID fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long playerId;
  private long productId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PPID() {}

  /**
   * All-args constructor.
   * @param playerId The new value for playerId
   * @param productId The new value for productId
   */
  public PPID(java.lang.Long playerId, java.lang.Long productId) {
    this.playerId = playerId;
    this.productId = productId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return playerId;
    case 1: return productId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: playerId = (java.lang.Long)value$; break;
    case 1: productId = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'playerId' field.
   * @return The value of the 'playerId' field.
   */
  public long getPlayerId() {
    return playerId;
  }


  /**
   * Sets the value of the 'playerId' field.
   * @param value the value to set.
   */
  public void setPlayerId(long value) {
    this.playerId = value;
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public long getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(long value) {
    this.productId = value;
  }

  /**
   * Creates a new PPID RecordBuilder.
   * @return A new PPID RecordBuilder
   */
  public static io.nermdev.schemas.avro.leaderboards.PPID.Builder newBuilder() {
    return new io.nermdev.schemas.avro.leaderboards.PPID.Builder();
  }

  /**
   * Creates a new PPID RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PPID RecordBuilder
   */
  public static io.nermdev.schemas.avro.leaderboards.PPID.Builder newBuilder(io.nermdev.schemas.avro.leaderboards.PPID.Builder other) {
    if (other == null) {
      return new io.nermdev.schemas.avro.leaderboards.PPID.Builder();
    } else {
      return new io.nermdev.schemas.avro.leaderboards.PPID.Builder(other);
    }
  }

  /**
   * Creates a new PPID RecordBuilder by copying an existing PPID instance.
   * @param other The existing instance to copy.
   * @return A new PPID RecordBuilder
   */
  public static io.nermdev.schemas.avro.leaderboards.PPID.Builder newBuilder(io.nermdev.schemas.avro.leaderboards.PPID other) {
    if (other == null) {
      return new io.nermdev.schemas.avro.leaderboards.PPID.Builder();
    } else {
      return new io.nermdev.schemas.avro.leaderboards.PPID.Builder(other);
    }
  }

  /**
   * RecordBuilder for PPID instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PPID>
    implements org.apache.avro.data.RecordBuilder<PPID> {

    private long playerId;
    private long productId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.nermdev.schemas.avro.leaderboards.PPID.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.playerId)) {
        this.playerId = data().deepCopy(fields()[0].schema(), other.playerId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing PPID instance
     * @param other The existing instance to copy.
     */
    private Builder(io.nermdev.schemas.avro.leaderboards.PPID other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.playerId)) {
        this.playerId = data().deepCopy(fields()[0].schema(), other.playerId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'playerId' field.
      * @return The value.
      */
    public long getPlayerId() {
      return playerId;
    }


    /**
      * Sets the value of the 'playerId' field.
      * @param value The value of 'playerId'.
      * @return This builder.
      */
    public io.nermdev.schemas.avro.leaderboards.PPID.Builder setPlayerId(long value) {
      validate(fields()[0], value);
      this.playerId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'playerId' field has been set.
      * @return True if the 'playerId' field has been set, false otherwise.
      */
    public boolean hasPlayerId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'playerId' field.
      * @return This builder.
      */
    public io.nermdev.schemas.avro.leaderboards.PPID.Builder clearPlayerId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public long getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public io.nermdev.schemas.avro.leaderboards.PPID.Builder setProductId(long value) {
      validate(fields()[1], value);
      this.productId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public io.nermdev.schemas.avro.leaderboards.PPID.Builder clearProductId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PPID build() {
      try {
        PPID record = new PPID();
        record.playerId = fieldSetFlags()[0] ? this.playerId : (java.lang.Long) defaultValue(fields()[0]);
        record.productId = fieldSetFlags()[1] ? this.productId : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PPID>
    WRITER$ = (org.apache.avro.io.DatumWriter<PPID>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PPID>
    READER$ = (org.apache.avro.io.DatumReader<PPID>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.playerId);

    out.writeLong(this.productId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.playerId = in.readLong();

      this.productId = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.playerId = in.readLong();
          break;

        case 1:
          this.productId = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










